apiVersion: apps/v1
kind: Deployment

metadata:
  name: swiggy-app-v1
  namespace: karthik

spec:
  replicas: 2

  selector:
    matchLabels:
      app: swiggy-app-v1

  template:
    metadata:
      labels:
        app: swiggy-app-v1

    spec:
      containers:
      - name: swiggy-app-v1
        image: manlineroot12/swiggy-app:latest

        env:
        - name: HOST
          value: "0.0.0.0"

        - name: PORT
          value: "5000"

        ports:
        - containerPort: 5000




