apiVersion: v1
kind: Service
metadata:
  name: swiggy-app-v1
  namespace: karthik
  labels:
    app: swiggy-app-v1
spec:
  selector:
    app: swiggy-app-v1
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
    nodePort: 30080
  type: NodePort
  


